---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicex-int-uproot-kustomization
  namespace: servicex-int-uproot

resources:
  - servicex-repository.yaml
  - values.yaml
  - servicex-int-uproot-sealed-secret.yaml
  - servicex-int-uproot-sealed-slack.yaml
  - slack-notification.yaml

