---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: servicex-jobs-branch
  namespace: servicex-testing-1
spec:
  interval: 5m
  url: https://github.com/ssl-hep/ServiceX.git
  ref:
    branch: 1504-change-transformer-k8s-resource-type-from-deployment-to-job
